// Generated by `pnpm --filter @games/decrypto-server generate:embeddings`.
// Do not edit by hand.

import { existsSync, readFileSync, statSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

type StoredTermsPayload = {
  terms: string[];
  targetTerms: string[];
  targetEmbeddingInputs?: Record<string, string>;
};

type StoredEmbeddingAssetStatus = {
  terms: number;
  targetTerms: number;
  dimensions: number;
  vectorBytes: number;
  expectedVectorBytes: number;
};

export const STORED_EMBEDDING_PROVIDER = 'openai';
export const STORED_EMBEDDING_MODEL = 'text-embedding-3-large';
export const STORED_EMBEDDING_DIMENSIONS = 384;
export const STORED_EMBEDDING_NORMALIZED = true;
export const STORED_EMBEDDING_QUANTIZATION = 'int8/127';
export const STORED_EMBEDDINGS_GENERATED_AT = '2026-06-19T02:04:52.693Z';
export const STORED_EMBEDDING_METADATA = {
  provider: 'openai',
  model: 'text-embedding-3-large',
  vocabularySize: 150000,
  targetVocabularySize: 440,
  generatedAt: '2026-06-19T02:04:52.693Z',
  source: {
    library: 'wordfreq',
    language: 'en',
    filterSettings: {
      requestedLimit: 150000,
      sourcePoolSize: null,
      wordfreqWordlist: 'best',
      fullWordlist: true,
      scanned: 164527,
      accepted: 150000,
      zipfFrequencyFloor: 1.5,
      minLength: 3,
      maxLength: 18,
      alphabeticOnly: true,
      allowHyphen: false,
      lowercaseOnly: true,
      profanityAdultTermsExcluded: false,
      stopwordCount: 325,
      rejected: {
        format: 13482,
        length: 755,
        stopword: 290,
        frequency: 0,
        duplicate: 0,
      },
    },
    forcedTargetTerms: 440,
    forcedSupplementalTerms: 1,
    guessEmbeddingInput:
      'Guess terms are embedded directly from the submitted/display word text after normalized vocabulary lookup.',
    targetEmbeddingInput:
      'Decrypto target terms are embedded directly from the card displayWord; exact target input strings are in keywordTerms.generated.json targetEmbeddingInputs.',
  },
  embedding: {
    dimensions: 384,
    normalized: true,
    requestedDimensions: 384,
    dimensionalityReduction:
      'OpenAI embeddings API dimensions parameter; vectors are normalized locally before int8 quantization',
    quantization: 'int8/127',
    runtimeVectorFormat:
      'keywordEmbeddings.int8.bin loaded lazily as an Int8Array; guess vectors are stored first, target vectors second; cosine uses int8 dot product divided by precomputed int8 norms, with no full Float32 matrix materialized',
  },
  assets: {
    vectors: 'keywordEmbeddings.int8.bin',
    terms: 'keywordTerms.generated.json',
    metadata: 'keywordEmbeddings.metadata.generated.json',
  },
  scoring: {
    rawCosine: 'cosine approximation over normalized OpenAI embeddings after int8 quantization',
    transformation:
      'runtime tiebreaker scoring compares each guess vector to the corresponding target display-word vector, calibrates raw cosine against generated target-word cosine distribution, and caps non-exact matches below 1',
  },
} as const;
export const STORED_EMBEDDING_ASSET_FILES = {
  vectors: 'keywordEmbeddings.int8.bin',
  terms: 'keywordTerms.generated.json',
  metadata: 'keywordEmbeddings.metadata.generated.json',
} as const;
export const STORED_EMBEDDING_SCORE_FLOOR = 0.204105;
export const STORED_EMBEDDING_SCORE_CEILING = 0.453805;

let termsPayloadCache: StoredTermsPayload | undefined;
let termIndexCache: Map<string, number> | undefined;
let targetIndexCache: Map<string, number> | undefined;
let vectorBytesCache: Int8Array | undefined;
let vectorNormCache: Float32Array | undefined;

function assetPath(filename: string): string {
  const currentDir = dirname(fileURLToPath(import.meta.url));
  const candidates = [resolve(currentDir, filename), resolve(currentDir, '../src', filename)];
  const found = candidates.find((candidate) => existsSync(candidate));
  if (!found) throw new Error(`Missing generated Decrypto embedding asset: ${filename}`);
  return found;
}

function loadTermsPayload(): StoredTermsPayload {
  termsPayloadCache ??= JSON.parse(
    readFileSync(assetPath(STORED_EMBEDDING_ASSET_FILES.terms), 'utf8'),
  ) as StoredTermsPayload;
  if (!Array.isArray(termsPayloadCache.terms) || !Array.isArray(termsPayloadCache.targetTerms)) {
    throw new Error('Generated Decrypto embedding terms asset has an invalid shape.');
  }
  return termsPayloadCache;
}

function termIndexMap(): Map<string, number> {
  termIndexCache ??= new Map(loadTermsPayload().terms.map((term, index) => [term, index]));
  return termIndexCache;
}

function targetIndexMap(): Map<string, number> {
  targetIndexCache ??= new Map(loadTermsPayload().targetTerms.map((term, index) => [term, index]));
  return targetIndexCache;
}

function totalVectorCount(): number {
  const termsPayload = loadTermsPayload();
  return termsPayload.terms.length + termsPayload.targetTerms.length;
}

function targetVectorIndex(targetIndex: number): number {
  return getStoredEmbeddingTerms().length + targetIndex;
}

function vectorBytes(): Int8Array {
  if (vectorBytesCache) return vectorBytesCache;
  const buffer = readFileSync(assetPath(STORED_EMBEDDING_ASSET_FILES.vectors));
  const expectedLength = totalVectorCount() * STORED_EMBEDDING_DIMENSIONS;
  if (buffer.byteLength !== expectedLength) {
    throw new Error(
      `Generated Decrypto embedding vector asset has ${buffer.byteLength} bytes; expected ${expectedLength}.`,
    );
  }
  vectorBytesCache = new Int8Array(buffer.buffer, buffer.byteOffset, buffer.byteLength);
  return vectorBytesCache;
}

function vectorNorms(): Float32Array {
  if (vectorNormCache) return vectorNormCache;
  const bytes = vectorBytes();
  const norms = new Float32Array(totalVectorCount());
  for (let vectorIndex = 0; vectorIndex < norms.length; vectorIndex += 1) {
    const offset = vectorIndex * STORED_EMBEDDING_DIMENSIONS;
    let magnitude = 0;
    for (let dimension = 0; dimension < STORED_EMBEDDING_DIMENSIONS; dimension += 1) {
      const value = bytes[offset + dimension] ?? 0;
      magnitude += value * value;
    }
    norms[vectorIndex] = Math.sqrt(magnitude);
  }
  vectorNormCache = norms;
  return norms;
}

function assertVectorIndex(index: number): void {
  if (!Number.isInteger(index) || index < 0 || index >= totalVectorCount()) {
    throw new Error(`Stored Decrypto embedding index out of range: ${index}`);
  }
}

export function getStoredEmbeddingTerms(): readonly string[] {
  return loadTermsPayload().terms;
}

export function getStoredTargetEmbeddingTerms(): readonly string[] {
  return loadTermsPayload().targetTerms;
}

export function getStoredTargetEmbeddingInputs(): Readonly<Record<string, string>> {
  return loadTermsPayload().targetEmbeddingInputs ?? {};
}

export function getStoredEmbeddingIndex(term: string): number | undefined {
  return termIndexMap().get(term);
}

export function getStoredTargetEmbeddingIndex(term: string): number | undefined {
  return targetIndexMap().get(term);
}

export function hasStoredEmbeddingTerm(term: string): boolean {
  return getStoredEmbeddingIndex(term) !== undefined;
}

export function assertStoredEmbeddingAssetsAvailable(): StoredEmbeddingAssetStatus {
  const termsPayload = loadTermsPayload();
  const metadataPath = assetPath(STORED_EMBEDDING_ASSET_FILES.metadata);
  const metadata = JSON.parse(readFileSync(metadataPath, 'utf8')) as {
    vocabularySize?: number;
    targetVocabularySize?: number;
    embedding?: { dimensions?: number };
  };

  if (termsPayload.terms.length !== STORED_EMBEDDING_METADATA.vocabularySize) {
    throw new Error(
      `Generated Decrypto embedding terms asset has ${termsPayload.terms.length} terms; expected ${STORED_EMBEDDING_METADATA.vocabularySize}.`,
    );
  }
  if (termsPayload.targetTerms.length !== STORED_EMBEDDING_METADATA.targetVocabularySize) {
    throw new Error(
      `Generated Decrypto target terms asset has ${termsPayload.targetTerms.length} terms; expected ${STORED_EMBEDDING_METADATA.targetVocabularySize}.`,
    );
  }
  if (
    metadata.vocabularySize !== STORED_EMBEDDING_METADATA.vocabularySize ||
    metadata.targetVocabularySize !== STORED_EMBEDDING_METADATA.targetVocabularySize ||
    metadata.embedding?.dimensions !== STORED_EMBEDDING_DIMENSIONS
  ) {
    throw new Error('Generated Decrypto embedding metadata asset does not match the compiled loader metadata.');
  }

  const vectorPath = assetPath(STORED_EMBEDDING_ASSET_FILES.vectors);
  const vectorBytes = statSync(vectorPath).size;
  const expectedVectorBytes = totalVectorCount() * STORED_EMBEDDING_DIMENSIONS;
  if (vectorBytes !== expectedVectorBytes) {
    throw new Error(
      `Generated Decrypto embedding vector asset has ${vectorBytes} bytes; expected ${expectedVectorBytes}.`,
    );
  }

  return {
    terms: termsPayload.terms.length,
    targetTerms: termsPayload.targetTerms.length,
    dimensions: STORED_EMBEDDING_DIMENSIONS,
    vectorBytes,
    expectedVectorBytes,
  };
}

export function storedEmbeddingInt8Norm(index: number): number {
  assertVectorIndex(index);
  return vectorNorms()[index] ?? 0;
}

export function storedEmbeddingCosineByIndex(leftIndex: number, rightIndex: number): number {
  assertVectorIndex(leftIndex);
  assertVectorIndex(rightIndex);
  const leftNorm = storedEmbeddingInt8Norm(leftIndex);
  const rightNorm = storedEmbeddingInt8Norm(rightIndex);
  if (leftNorm === 0 || rightNorm === 0) return 0;

  const bytes = vectorBytes();
  const leftOffset = leftIndex * STORED_EMBEDDING_DIMENSIONS;
  const rightOffset = rightIndex * STORED_EMBEDDING_DIMENSIONS;
  let dot = 0;
  for (let dimension = 0; dimension < STORED_EMBEDDING_DIMENSIONS; dimension += 1) {
    dot += (bytes[leftOffset + dimension] ?? 0) * (bytes[rightOffset + dimension] ?? 0);
  }
  return dot / (leftNorm * rightNorm);
}

export function storedTargetEmbeddingCosineByIndex(guessIndex: number, targetIndex: number): number {
  return storedEmbeddingCosineByIndex(guessIndex, targetVectorIndex(targetIndex));
}

export function storedEmbeddingCosineByTerm(leftTerm: string, rightTerm: string): number | undefined {
  const leftIndex = getStoredEmbeddingIndex(leftTerm);
  const rightIndex = getStoredEmbeddingIndex(rightTerm);
  return leftIndex === undefined || rightIndex === undefined
    ? undefined
    : storedEmbeddingCosineByIndex(leftIndex, rightIndex);
}

export function storedTargetEmbeddingCosineByTerm(guessTerm: string, targetTerm: string): number | undefined {
  const guessIndex = getStoredEmbeddingIndex(guessTerm);
  const targetIndex = getStoredTargetEmbeddingIndex(targetTerm);
  return guessIndex === undefined || targetIndex === undefined
    ? undefined
    : storedTargetEmbeddingCosineByIndex(guessIndex, targetIndex);
}

function dequantizedNormalizedVector(index: number): Float32Array {
  assertVectorIndex(index);
  const bytes = vectorBytes();
  const offset = index * STORED_EMBEDDING_DIMENSIONS;
  const vector = new Float32Array(STORED_EMBEDDING_DIMENSIONS);
  let magnitude = 0;
  for (let dimension = 0; dimension < STORED_EMBEDDING_DIMENSIONS; dimension += 1) {
    const value = (bytes[offset + dimension] ?? 0) / 127;
    vector[dimension] = value;
    magnitude += value * value;
  }
  if (magnitude === 0) return vector;
  const scale = 1 / Math.sqrt(magnitude);
  for (let dimension = 0; dimension < vector.length; dimension += 1) vector[dimension] *= scale;
  return vector;
}

export function referenceDequantizedCosineByIndex(leftIndex: number, rightIndex: number): number {
  const left = dequantizedNormalizedVector(leftIndex);
  const right = dequantizedNormalizedVector(rightIndex);
  let dot = 0;
  for (let dimension = 0; dimension < STORED_EMBEDDING_DIMENSIONS; dimension += 1) {
    dot += (left[dimension] ?? 0) * (right[dimension] ?? 0);
  }
  return dot;
}

export function referenceDequantizedTargetCosineByIndex(guessIndex: number, targetIndex: number): number {
  return referenceDequantizedCosineByIndex(guessIndex, targetVectorIndex(targetIndex));
}
